# Generated by Django 4.2 on 2025-01-01 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PFApp', '0004_alter_suscripcion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='periodo_facturacion',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], max_length=50),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
